name: assignment-test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  full-test:
    container: cuaesd/aesd-autotest:24-assignment6
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive   # pull all valid submodules
          fetch-depth: 0          # avoid shallow clone issues
      - name: Run full test
        run: ./full-test.sh

