name: assignment-test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  full-test:
    container: cuaesd/aesd-autotest:24-assignment6
    runs-on: self-hosted
    steps:
      - name: Checkout repo (no recursive submodules)
        uses: actions/checkout@v2
        with:
          submodules: false

      - name: Init only assignment-autotest submodule
        run: git submodule update --init assignment-autotest

      - name: Run full test
        run: ./full-test.sh

