name: assignment-test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  full-test:
    container: cuaesd/aesd-autotest:24-assignment6
    runs-on: self-hosted
    steps:
      - name: Checkout repo (force clean, no stale submodules)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          clean: true
          submodules: false   # don't pull all, we’ll init only the one we want

      - name: Init only assignment-autotest submodule
        run: git submodule update --init assignment-autotest

      - name: Run full test
        run: ./full-test.sh

